# Generated by Django 3.1.5 on 2022-06-12 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_index=True, editable=False, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='friend_creator', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('friend_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='friend_friend_user', to=settings.AUTH_USER_MODEL, verbose_name='Friend')),
            ],
            options={
                'verbose_name': 'Amigo',
                'verbose_name_plural': 'Amigos',
                'unique_together': {('creator', 'friend_user')},
            },
        ),
    ]
